name: CI

on:
  push:
    branches:
      - main

jobs:
  pruebas:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Instalar dependencias
        working-directory: api
        run: npm install

      - name: Ejecutar pruebas
        working-directory: api
        run: npm test
